global:
  smtp_smarthost: 'localhost:25'
  smtp_from: 'root@prometheus'
  smtp_auth_username: ''
  smtp_auth_password: ''
  smtp_require_tls: false

templates:
- '/etc/alertmanager/template/*.tmpl'

route:
  repeat_interval: 1h
# default receiver
  receiver: operations-team
  routes:
#    - receiver: "paging-chat"
#      group_wait: 10s
#      match_re:
#        severity: critical
##       alertname: ServiceDown
#      continue: true

    - receiver: "service-management"
      group_wait: 10s
      match_re:
        severity: critical|warning
      continue: true

receivers:
- name: 'operations-team'
  email_configs:
  - to: 'venkatesh.yadavali@gmail.com'
#  - to: 'venkatesh.yadavali@gmail.com, y.heryanto@gmail.com'
    send_resolved: true
- name: 'service-management'
  email_configs:
  - to: 'venkatesh_yadavali@yahoo.com'
    send_resolved: true
- name: 'paging-chat'
  webhook_configs:
  - url: 'http://localhost:2000/high_priority_MSteams_channel'
    send_resolved: true
# URL of MS teams channel  - url: 'https://outlook.office.com/webhook/57333b53-f777-4e7f-93fe-83f27fe289ae@7107009f-dccf-4349-8e1b-b1513556e5c5/IncomingWebhook/8b657a13284548c2ae0b07594b10d0e5/8fdfc2d8-75eb-4b1d-8ab4-c4867101eaf2'
